---
name: build-web-image-workflow
on:
  - push
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker build \
            -t rhhilario-hub/ch09-demo-app/web:ch09 \
            web